version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: foodgram-db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: lkofe1/foodgram_backend:latest
    container_name: foodgram-backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: lkofe1/foodgram_frontend:latest
    container_name: foodgram-front
    restart: always
    volumes:
      - html_value:/app/result_build/

  nginx:
    image: lkofe1/foodgram_gateway:latest
    container_name: foodgram-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html_value:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  html_value:
  static_value:
  media_value: